name: Deployment (Container)
on:
  push:
    branches:
      - master
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest #This machine will now host the image, but the jobs will run in the container image
    #container: node:16 #Can use publicly available images from dockerhub
    container:
      image: node:16
      #env: #Can define env variables for the image
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb #mongodb+srv
      MONGODB_CLUSTER_ADDRESS: mongodb #Establishes a network connection to the services db in the container
      MONGODB_USERNAME: root #${{ secrets.MONGODB_USERNAME }} Chaged to use the image db
      MONGODB_PASSWORD: example #${{ secrets.MONGODB_PASSWORD }} Chaged to use the image db
      PORT: 8080
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
